name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex    # "ubuntu" is a more generic container
                               # using "pandoc/latex" because of dependencies
                               # used in the specific "build.sh"
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.COPY_REPO }}
        with:
          source-directory: 'pages'
          destination-github-username: 'walter-lkmx'
          destination-repository-name: 'lkmx-design-knowledge'
          target-directory: 'pages'
          user-email: walter.hurtado@lkmx.io
          target-branch: main
